module VatSense
  module Models
    module Invoice
      type item_retrieve_params =
        { invoice_id: String, item_id: String }
        & VatSense::Internal::Type::request_parameters

      class ItemRetrieveParams < VatSense::Internal::Type::BaseModel
        extend VatSense::Internal::Type::RequestParameters::Converter
        include VatSense::Internal::Type::RequestParameters

        attr_accessor invoice_id: String

        attr_accessor item_id: String

        def initialize: (
          invoice_id: String,
          item_id: String,
          ?request_options: VatSense::request_opts
        ) -> void

        def to_hash: -> {
          invoice_id: String,
          item_id: String,
          request_options: VatSense::RequestOptions
        }
      end
    end
  end
end
