module VatSense
  module Resources
    class Countries
      def list: (
        ?country_code: String,
        ?ip_address: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::CountryListResponse

      def list_provinces: (
        country_code: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::CountryListProvincesResponse

      def initialize: (client: VatSense::Client) -> void
    end
  end
end
