module VatSense
  module Resources
    class Currency
      def list: (
        ?from: String,
        ?to: VatSense::Models::CurrencyListParams::to,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::CurrencyListResponse

      def calculate_vat_price: (
        price: String,
        tax_type: VatSense::Models::CurrencyCalculateVatPriceParams::tax_type,
        vat_rate: Float,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::CurrencyCalculateVatPriceResponse

      def convert: (
        amount: String,
        from: String,
        to: VatSense::Models::CurrencyConvertParams::to,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::CurrencyConvertResponse

      def initialize: (client: VatSense::Client) -> void
    end
  end
end
