module VatSense
  module Resources
    class Rates
      def list: (
        ?country_code: String,
        ?eu: bool,
        ?ip_address: String,
        ?period: Time,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::RateListResponse

      def calculate_price: (
        price: String,
        tax_type: VatSense::Models::RateCalculatePriceParams::tax_type,
        ?country_code: String,
        ?eu: bool,
        ?ip_address: String,
        ?province_code: String,
        ?type: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::RateCalculatePriceResponse

      def details: (
        ?country_code: String,
        ?eu: bool,
        ?ip_address: String,
        ?period: Time,
        ?province_code: String,
        ?type: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::FindRate

      def find: (
        ?country_code: String,
        ?eu: bool,
        ?ip_address: String,
        ?period: Time,
        ?province_code: String,
        ?type: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::FindRate

      def list_types: (
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::RateListTypesResponse

      def initialize: (client: VatSense::Client) -> void
    end
  end
end
