module VatSense
  module Resources
    class Usage
      def retrieve: (
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::UsageRetrieveResponse

      def initialize: (client: VatSense::Client) -> void
    end
  end
end
