module VatSense
  module Resources
    class Validate
      def check: (
        ?eori_number: String,
        ?requester_vat_number: String,
        ?vat_number: String,
        ?request_options: VatSense::request_opts
      ) -> VatSense::Models::ValidateCheckResponse

      def initialize: (client: VatSense::Client) -> void
    end
  end
end
