module Vatsense
  module Models
    class InvoiceItemInput = Invoice::InvoiceItemInput

    module Invoice
      type invoice_item_input =
        {
          item: String,
          price_each: Float,
          quantity: Float,
          vat_rate: Float,
          discount_rate: Float
        }

      class InvoiceItemInput < Vatsense::Internal::Type::BaseModel
        attr_accessor item: String

        attr_accessor price_each: Float

        attr_accessor quantity: Float

        attr_accessor vat_rate: Float

        attr_reader discount_rate: Float?

        def discount_rate=: (Float) -> Float

        def initialize: (
          item: String,
          price_each: Float,
          quantity: Float,
          vat_rate: Float,
          ?discount_rate: Float
        ) -> void

        def to_hash: -> {
          item: String,
          price_each: Float,
          quantity: Float,
          vat_rate: Float,
          discount_rate: Float
        }
      end
    end
  end
end
