module Vatsense
  module Models
    module Invoice
      type item_update_params =
        { invoice_id: String, item_id: String }
        & Vatsense::Internal::Type::request_parameters

      class ItemUpdateParams < Vatsense::Models::Invoice::InvoiceItemInput
        extend Vatsense::Internal::Type::RequestParameters::Converter
        include Vatsense::Internal::Type::RequestParameters

        def invoice_id: -> String

        def invoice_id=: (String _) -> String

        def item_id: -> String

        def item_id=: (String _) -> String

        def initialize: (
          invoice_id: String,
          item_id: String,
          ?request_options: Vatsense::request_opts
        ) -> void

        def to_hash: -> {
          invoice_id: String,
          item_id: String,
          request_options: Vatsense::RequestOptions
        }
      end
    end
  end
end
