module Vatsense
  class Client < Vatsense::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader username: String

    attr_reader password: String

    attr_reader rates: Vatsense::Resources::Rates

    attr_reader countries: Vatsense::Resources::Countries

    attr_reader validate: Vatsense::Resources::Validate

    attr_reader currency: Vatsense::Resources::Currency

    attr_reader invoice: Vatsense::Resources::Invoice

    attr_reader usage: Vatsense::Resources::Usage

    attr_reader sandbox: Vatsense::Resources::Sandbox

    private def auth_headers: (
      security: { basic_auth: bool }
    ) -> ::Hash[String, String]

    private def basic_auth: -> ::Hash[String, String]

    def initialize: (
      ?username: String?,
      ?password: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
