# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "vatsense/version"
require_relative "vatsense/internal/util"
require_relative "vatsense/internal/type/converter"
require_relative "vatsense/internal/type/unknown"
require_relative "vatsense/internal/type/boolean"
require_relative "vatsense/internal/type/file_input"
require_relative "vatsense/internal/type/enum"
require_relative "vatsense/internal/type/union"
require_relative "vatsense/internal/type/array_of"
require_relative "vatsense/internal/type/hash_of"
require_relative "vatsense/internal/type/base_model"
require_relative "vatsense/internal/type/base_page"
require_relative "vatsense/internal/type/request_parameters"
require_relative "vatsense/internal"
require_relative "vatsense/request_options"
require_relative "vatsense/file_part"
require_relative "vatsense/errors"
require_relative "vatsense/internal/transport/base_client"
require_relative "vatsense/internal/transport/pooled_net_requester"
require_relative "vatsense/client"
require_relative "vatsense/models/invoice/invoice_item_input"
require_relative "vatsense/models/create_invoice"
require_relative "vatsense/models/tax_rate"
require_relative "vatsense/models/country"
require_relative "vatsense/models/country_list_params"
require_relative "vatsense/models/country_list_provinces_params"
require_relative "vatsense/models/country_list_provinces_response"
require_relative "vatsense/models/country_list_response"
require_relative "vatsense/models/currency_calculate_vat_price_params"
require_relative "vatsense/models/currency_calculate_vat_price_response"
require_relative "vatsense/models/currency_convert_params"
require_relative "vatsense/models/currency_convert_response"
require_relative "vatsense/models/currency_list_params"
require_relative "vatsense/models/currency_list_response"
require_relative "vatsense/models/find_rate"
require_relative "vatsense/models/invoice/invoice_item"
require_relative "vatsense/models/invoice/item_add_params"
require_relative "vatsense/models/invoice/item_delete_params"
require_relative "vatsense/models/invoice/item_retrieve_params"
require_relative "vatsense/models/invoice/item_retrieve_response"
require_relative "vatsense/models/invoice/item_update_params"
require_relative "vatsense/models/invoice"
require_relative "vatsense/models/invoice_business_input"
require_relative "vatsense/models/invoice_conversion_input"
require_relative "vatsense/models/invoice_create_params"
require_relative "vatsense/models/invoice_customer_input"
require_relative "vatsense/models/invoice_delete_params"
require_relative "vatsense/models/invoice_delete_response"
require_relative "vatsense/models/invoice_list_params"
require_relative "vatsense/models/invoice_list_response"
require_relative "vatsense/models/invoice_response"
require_relative "vatsense/models/invoice_retrieve_params"
require_relative "vatsense/models/invoice_update_params"
require_relative "vatsense/models/rate"
require_relative "vatsense/models/rate_calculate_price_params"
require_relative "vatsense/models/rate_calculate_price_response"
require_relative "vatsense/models/rate_details_params"
require_relative "vatsense/models/rate_find_params"
require_relative "vatsense/models/rate_list_params"
require_relative "vatsense/models/rate_list_response"
require_relative "vatsense/models/rate_list_types_params"
require_relative "vatsense/models/rate_list_types_response"
require_relative "vatsense/models/rate_with_tax_rate"
require_relative "vatsense/models/sandbox_generate_key_params"
require_relative "vatsense/models/sandbox_generate_key_response"
require_relative "vatsense/models/usage_retrieve_params"
require_relative "vatsense/models/usage_retrieve_response"
require_relative "vatsense/models/validate_check_params"
require_relative "vatsense/models/validate_check_response"
require_relative "vatsense/models/vat_price"
require_relative "vatsense/models"
require_relative "vatsense/resources/countries"
require_relative "vatsense/resources/currency"
require_relative "vatsense/resources/invoice"
require_relative "vatsense/resources/invoice/item"
require_relative "vatsense/resources/rates"
require_relative "vatsense/resources/sandbox"
require_relative "vatsense/resources/usage"
require_relative "vatsense/resources/validate"
