module Vatsense
  module Models
    type currency_convert_response =
      {
        code: Integer,
        data: Vatsense::Models::CurrencyConvertResponse::Data,
        success: bool
      }

    class CurrencyConvertResponse < Vatsense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: Vatsense::Models::CurrencyConvertResponse::Data?

      def data=: (
        Vatsense::Models::CurrencyConvertResponse::Data
      ) -> Vatsense::Models::CurrencyConvertResponse::Data

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: Vatsense::Models::CurrencyConvertResponse::Data,
        ?success: bool
      ) -> void

      def to_hash: -> {
        code: Integer,
        data: Vatsense::Models::CurrencyConvertResponse::Data,
        success: bool
      }

      type data =
        {
          amount: Float,
          converted: Float,
          from: String,
          object: Vatsense::Models::CurrencyConvertResponse::Data::object,
          rate: Float,
          to: String
        }

      class Data < Vatsense::Internal::Type::BaseModel
        attr_reader amount: Float?

        def amount=: (Float) -> Float

        attr_reader converted: Float?

        def converted=: (Float) -> Float

        attr_reader from: String?

        def from=: (String) -> String

        attr_reader object: Vatsense::Models::CurrencyConvertResponse::Data::object?

        def object=: (
          Vatsense::Models::CurrencyConvertResponse::Data::object
        ) -> Vatsense::Models::CurrencyConvertResponse::Data::object

        attr_reader rate: Float?

        def rate=: (Float) -> Float

        attr_reader to: String?

        def to=: (String) -> String

        def initialize: (
          ?amount: Float,
          ?converted: Float,
          ?from: String,
          ?object: Vatsense::Models::CurrencyConvertResponse::Data::object,
          ?rate: Float,
          ?to: String
        ) -> void

        def to_hash: -> {
          amount: Float,
          converted: Float,
          from: String,
          object: Vatsense::Models::CurrencyConvertResponse::Data::object,
          rate: Float,
          to: String
        }

        type object = :conversion

        module Object
          extend Vatsense::Internal::Type::Enum

          CONVERSION: :conversion

          def self?.values: -> ::Array[Vatsense::Models::CurrencyConvertResponse::Data::object]
        end
      end
    end
  end
end
