module Vatsense
  module Models
    type invoice_list_params =
      { limit: Integer, offset: Integer, search: String }
      & Vatsense::Internal::Type::request_parameters

    class InvoiceListParams < Vatsense::Internal::Type::BaseModel
      extend Vatsense::Internal::Type::RequestParameters::Converter
      include Vatsense::Internal::Type::RequestParameters

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_reader search: String?

      def search=: (String) -> String

      def initialize: (
        ?limit: Integer,
        ?offset: Integer,
        ?search: String,
        ?request_options: Vatsense::request_opts
      ) -> void

      def to_hash: -> {
        limit: Integer,
        offset: Integer,
        search: String,
        request_options: Vatsense::RequestOptions
      }
    end
  end
end
