module Vatsense
  module Models
    type invoice_business_input =
      {
        address: String,
        name: String,
        vat_number: String,
        bank_account: String,
        company_number: String,
        email: String,
        logo: String,
        phone: String,
        website: String
      }

    class InvoiceBusinessInput < Vatsense::Internal::Type::BaseModel
      attr_accessor address: String

      attr_accessor name: String

      attr_accessor vat_number: String

      attr_reader bank_account: String?

      def bank_account=: (String) -> String

      attr_reader company_number: String?

      def company_number=: (String) -> String

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader logo: String?

      def logo=: (String) -> String

      attr_reader phone: String?

      def phone=: (String) -> String

      attr_reader website: String?

      def website=: (String) -> String

      def initialize: (
        address: String,
        name: String,
        vat_number: String,
        ?bank_account: String,
        ?company_number: String,
        ?email: String,
        ?logo: String,
        ?phone: String,
        ?website: String
      ) -> void

      def to_hash: -> {
        address: String,
        name: String,
        vat_number: String,
        bank_account: String,
        company_number: String,
        email: String,
        logo: String,
        phone: String,
        website: String
      }
    end
  end
end
