module Vatsense
  module Models
    type rate_calculate_price_response =
      {
        code: Integer,
        data: Vatsense::Models::RateCalculatePriceResponse::Data,
        success: bool
      }

    class RateCalculatePriceResponse < Vatsense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: Vatsense::Models::RateCalculatePriceResponse::Data?

      def data=: (
        Vatsense::Models::RateCalculatePriceResponse::Data
      ) -> Vatsense::Models::RateCalculatePriceResponse::Data

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: Vatsense::Models::RateCalculatePriceResponse::Data,
        ?success: bool
      ) -> void

      def to_hash: -> {
        code: Integer,
        data: Vatsense::Models::RateCalculatePriceResponse::Data,
        success: bool
      }

      type data =
        {
          country_code: String,
          country_name: String,
          eu: bool,
          object: Vatsense::Models::RateCalculatePriceResponse::Data::object,
          tax_rate: Vatsense::TaxRate,
          vat_price: Vatsense::VatPrice
        }

      class Data < Vatsense::Internal::Type::BaseModel
        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader country_name: String?

        def country_name=: (String) -> String

        attr_reader eu: bool?

        def eu=: (bool) -> bool

        attr_reader object: Vatsense::Models::RateCalculatePriceResponse::Data::object?

        def object=: (
          Vatsense::Models::RateCalculatePriceResponse::Data::object
        ) -> Vatsense::Models::RateCalculatePriceResponse::Data::object

        attr_reader tax_rate: Vatsense::TaxRate?

        def tax_rate=: (Vatsense::TaxRate) -> Vatsense::TaxRate

        attr_reader vat_price: Vatsense::VatPrice?

        def vat_price=: (Vatsense::VatPrice) -> Vatsense::VatPrice

        def initialize: (
          ?country_code: String,
          ?country_name: String,
          ?eu: bool,
          ?object: Vatsense::Models::RateCalculatePriceResponse::Data::object,
          ?tax_rate: Vatsense::TaxRate,
          ?vat_price: Vatsense::VatPrice
        ) -> void

        def to_hash: -> {
          country_code: String,
          country_name: String,
          eu: bool,
          object: Vatsense::Models::RateCalculatePriceResponse::Data::object,
          tax_rate: Vatsense::TaxRate,
          vat_price: Vatsense::VatPrice
        }

        type object = :rate

        module Object
          extend Vatsense::Internal::Type::Enum

          RATE: :rate

          def self?.values: -> ::Array[Vatsense::Models::RateCalculatePriceResponse::Data::object]
        end
      end
    end
  end
end
