module Vatsense
  module Models
    type rate_list_types_response =
      { code: Integer, data: ::Array[String], success: bool }

    class RateListTypesResponse < Vatsense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: ::Array[String]?

      def data=: (::Array[String]) -> ::Array[String]

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: ::Array[String],
        ?success: bool
      ) -> void

      def to_hash: -> { code: Integer, data: ::Array[String], success: bool }
    end
  end
end
