module Vatsense
  module Models
    type vat_price =
      {
        object: Vatsense::Models::VatPrice::object,
        price: Float,
        price_excl_vat: Float,
        price_incl_vat: Float,
        tax_type: Vatsense::Models::VatPrice::tax_type,
        vat: Float,
        vat_rate: Float
      }

    class VatPrice < Vatsense::Internal::Type::BaseModel
      attr_reader object: Vatsense::Models::VatPrice::object?

      def object=: (
        Vatsense::Models::VatPrice::object
      ) -> Vatsense::Models::VatPrice::object

      attr_reader price: Float?

      def price=: (Float) -> Float

      attr_reader price_excl_vat: Float?

      def price_excl_vat=: (Float) -> Float

      attr_reader price_incl_vat: Float?

      def price_incl_vat=: (Float) -> Float

      attr_reader tax_type: Vatsense::Models::VatPrice::tax_type?

      def tax_type=: (
        Vatsense::Models::VatPrice::tax_type
      ) -> Vatsense::Models::VatPrice::tax_type

      attr_reader vat: Float?

      def vat=: (Float) -> Float

      attr_reader vat_rate: Float?

      def vat_rate=: (Float) -> Float

      def initialize: (
        ?object: Vatsense::Models::VatPrice::object,
        ?price: Float,
        ?price_excl_vat: Float,
        ?price_incl_vat: Float,
        ?tax_type: Vatsense::Models::VatPrice::tax_type,
        ?vat: Float,
        ?vat_rate: Float
      ) -> void

      def to_hash: -> {
        object: Vatsense::Models::VatPrice::object,
        price: Float,
        price_excl_vat: Float,
        price_incl_vat: Float,
        tax_type: Vatsense::Models::VatPrice::tax_type,
        vat: Float,
        vat_rate: Float
      }

      type object = :vat_price

      module Object
        extend Vatsense::Internal::Type::Enum

        VAT_PRICE: :vat_price

        def self?.values: -> ::Array[Vatsense::Models::VatPrice::object]
      end

      type tax_type = :incl | :excl

      module TaxType
        extend Vatsense::Internal::Type::Enum

        INCL: :incl
        EXCL: :excl

        def self?.values: -> ::Array[Vatsense::Models::VatPrice::tax_type]
      end
    end
  end
end
