module VatSense
  module Models
    type country_list_provinces_response =
      {
        code: Integer,
        data: ::Array[VatSense::Models::CountryListProvincesResponse::Data],
        success: bool
      }

    class CountryListProvincesResponse < VatSense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: ::Array[VatSense::Models::CountryListProvincesResponse::Data]?

      def data=: (
        ::Array[VatSense::Models::CountryListProvincesResponse::Data]
      ) -> ::Array[VatSense::Models::CountryListProvincesResponse::Data]

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: ::Array[VatSense::Models::CountryListProvincesResponse::Data],
        ?success: bool
      ) -> void

      def to_hash: -> {
        code: Integer,
        data: ::Array[VatSense::Models::CountryListProvincesResponse::Data],
        success: bool
      }

      type data =
        {
          country_code: String,
          object: VatSense::Models::CountryListProvincesResponse::Data::object,
          province_code: String,
          province_name: String
        }

      class Data < VatSense::Internal::Type::BaseModel
        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader object: VatSense::Models::CountryListProvincesResponse::Data::object?

        def object=: (
          VatSense::Models::CountryListProvincesResponse::Data::object
        ) -> VatSense::Models::CountryListProvincesResponse::Data::object

        attr_reader province_code: String?

        def province_code=: (String) -> String

        attr_reader province_name: String?

        def province_name=: (String) -> String

        def initialize: (
          ?country_code: String,
          ?object: VatSense::Models::CountryListProvincesResponse::Data::object,
          ?province_code: String,
          ?province_name: String
        ) -> void

        def to_hash: -> {
          country_code: String,
          object: VatSense::Models::CountryListProvincesResponse::Data::object,
          province_code: String,
          province_name: String
        }

        type object = :province

        module Object
          extend VatSense::Internal::Type::Enum

          PROVINCE: :province

          def self?.values: -> ::Array[VatSense::Models::CountryListProvincesResponse::Data::object]
        end
      end
    end
  end
end
