module VatSense
  module Models
    type country_list_provinces_params =
      { country_code: String } & VatSense::Internal::Type::request_parameters

    class CountryListProvincesParams < VatSense::Internal::Type::BaseModel
      extend VatSense::Internal::Type::RequestParameters::Converter
      include VatSense::Internal::Type::RequestParameters

      attr_accessor country_code: String

      def initialize: (
        country_code: String,
        ?request_options: VatSense::request_opts
      ) -> void

      def to_hash: -> {
        country_code: String,
        request_options: VatSense::RequestOptions
      }
    end
  end
end
