module VatSense
  module Models
    type create_invoice =
      {
        business: VatSense::InvoiceBusinessInput,
        currency_code: String,
        date: String,
        items: ::Array[VatSense::Invoice::InvoiceItemInput],
        tax_point: String,
        conversion: VatSense::InvoiceConversionInput,
        customer: VatSense::InvoiceCustomerInput,
        has_vat: bool,
        invoice_number: String,
        is_copy: bool,
        is_reverse_charge: bool,
        notes: String,
        pad_invoice_number: Integer,
        serial: String,
        tax_type: VatSense::Models::CreateInvoice::tax_type,
        type: VatSense::Models::CreateInvoice::type_,
        zero_rated: bool
      }

    class CreateInvoice < VatSense::Internal::Type::BaseModel
      attr_accessor business: VatSense::InvoiceBusinessInput

      attr_accessor currency_code: String

      attr_accessor date: String

      attr_accessor items: ::Array[VatSense::Invoice::InvoiceItemInput]

      attr_accessor tax_point: String

      attr_reader conversion: VatSense::InvoiceConversionInput?

      def conversion=: (
        VatSense::InvoiceConversionInput
      ) -> VatSense::InvoiceConversionInput

      attr_reader customer: VatSense::InvoiceCustomerInput?

      def customer=: (
        VatSense::InvoiceCustomerInput
      ) -> VatSense::InvoiceCustomerInput

      attr_reader has_vat: bool?

      def has_vat=: (bool) -> bool

      attr_reader invoice_number: String?

      def invoice_number=: (String) -> String

      attr_reader is_copy: bool?

      def is_copy=: (bool) -> bool

      attr_reader is_reverse_charge: bool?

      def is_reverse_charge=: (bool) -> bool

      attr_reader notes: String?

      def notes=: (String) -> String

      attr_reader pad_invoice_number: Integer?

      def pad_invoice_number=: (Integer) -> Integer

      attr_reader serial: String?

      def serial=: (String) -> String

      attr_reader tax_type: VatSense::Models::CreateInvoice::tax_type?

      def tax_type=: (
        VatSense::Models::CreateInvoice::tax_type
      ) -> VatSense::Models::CreateInvoice::tax_type

      attr_reader type: VatSense::Models::CreateInvoice::type_?

      def type=: (
        VatSense::Models::CreateInvoice::type_
      ) -> VatSense::Models::CreateInvoice::type_

      attr_reader zero_rated: bool?

      def zero_rated=: (bool) -> bool

      def initialize: (
        business: VatSense::InvoiceBusinessInput,
        currency_code: String,
        date: String,
        items: ::Array[VatSense::Invoice::InvoiceItemInput],
        tax_point: String,
        ?conversion: VatSense::InvoiceConversionInput,
        ?customer: VatSense::InvoiceCustomerInput,
        ?has_vat: bool,
        ?invoice_number: String,
        ?is_copy: bool,
        ?is_reverse_charge: bool,
        ?notes: String,
        ?pad_invoice_number: Integer,
        ?serial: String,
        ?tax_type: VatSense::Models::CreateInvoice::tax_type,
        ?type: VatSense::Models::CreateInvoice::type_,
        ?zero_rated: bool
      ) -> void

      def to_hash: -> {
        business: VatSense::InvoiceBusinessInput,
        currency_code: String,
        date: String,
        items: ::Array[VatSense::Invoice::InvoiceItemInput],
        tax_point: String,
        conversion: VatSense::InvoiceConversionInput,
        customer: VatSense::InvoiceCustomerInput,
        has_vat: bool,
        invoice_number: String,
        is_copy: bool,
        is_reverse_charge: bool,
        notes: String,
        pad_invoice_number: Integer,
        serial: String,
        tax_type: VatSense::Models::CreateInvoice::tax_type,
        type: VatSense::Models::CreateInvoice::type_,
        zero_rated: bool
      }

      type tax_type = :incl | :excl

      module TaxType
        extend VatSense::Internal::Type::Enum

        INCL: :incl
        EXCL: :excl

        def self?.values: -> ::Array[VatSense::Models::CreateInvoice::tax_type]
      end

      type type_ = :sale | :refund

      module Type
        extend VatSense::Internal::Type::Enum

        SALE: :sale
        REFUND: :refund

        def self?.values: -> ::Array[VatSense::Models::CreateInvoice::type_]
      end
    end
  end
end
