module VatSense
  module Models
    type currency_list_params =
      { from: String, to: VatSense::Models::CurrencyListParams::to }
      & VatSense::Internal::Type::request_parameters

    class CurrencyListParams < VatSense::Internal::Type::BaseModel
      extend VatSense::Internal::Type::RequestParameters::Converter
      include VatSense::Internal::Type::RequestParameters

      attr_reader from: String?

      def from=: (String) -> String

      attr_reader to: VatSense::Models::CurrencyListParams::to?

      def to=: (
        VatSense::Models::CurrencyListParams::to
      ) -> VatSense::Models::CurrencyListParams::to

      def initialize: (
        ?from: String,
        ?to: VatSense::Models::CurrencyListParams::to,
        ?request_options: VatSense::request_opts
      ) -> void

      def to_hash: -> {
        from: String,
        to: VatSense::Models::CurrencyListParams::to,
        request_options: VatSense::RequestOptions
      }

      type to = :GBP | :EUR

      module To
        extend VatSense::Internal::Type::Enum

        GBP: :GBP
        EUR: :EUR

        def self?.values: -> ::Array[VatSense::Models::CurrencyListParams::to]
      end
    end
  end
end
