module VatSense
  module Models
    type currency_list_response =
      {
        code: Integer,
        data: ::Array[VatSense::Models::CurrencyListResponse::Data],
        success: bool
      }

    class CurrencyListResponse < VatSense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: ::Array[VatSense::Models::CurrencyListResponse::Data]?

      def data=: (
        ::Array[VatSense::Models::CurrencyListResponse::Data]
      ) -> ::Array[VatSense::Models::CurrencyListResponse::Data]

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: ::Array[VatSense::Models::CurrencyListResponse::Data],
        ?success: bool
      ) -> void

      def to_hash: -> {
        code: Integer,
        data: ::Array[VatSense::Models::CurrencyListResponse::Data],
        success: bool
      }

      type data =
        {
          from: String,
          object: VatSense::Models::CurrencyListResponse::Data::object,
          rate: Float,
          to: String
        }

      class Data < VatSense::Internal::Type::BaseModel
        attr_reader from: String?

        def from=: (String) -> String

        attr_reader object: VatSense::Models::CurrencyListResponse::Data::object?

        def object=: (
          VatSense::Models::CurrencyListResponse::Data::object
        ) -> VatSense::Models::CurrencyListResponse::Data::object

        attr_reader rate: Float?

        def rate=: (Float) -> Float

        attr_reader to: String?

        def to=: (String) -> String

        def initialize: (
          ?from: String,
          ?object: VatSense::Models::CurrencyListResponse::Data::object,
          ?rate: Float,
          ?to: String
        ) -> void

        def to_hash: -> {
          from: String,
          object: VatSense::Models::CurrencyListResponse::Data::object,
          rate: Float,
          to: String
        }

        type object = :convert_rate

        module Object
          extend VatSense::Internal::Type::Enum

          CONVERT_RATE: :convert_rate

          def self?.values: -> ::Array[VatSense::Models::CurrencyListResponse::Data::object]
        end
      end
    end
  end
end
