module VatSense
  module Models
    type currency_calculate_vat_price_response =
      { code: Integer, data: VatSense::VatPrice, success: bool }

    class CurrencyCalculateVatPriceResponse < VatSense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: VatSense::VatPrice?

      def data=: (VatSense::VatPrice) -> VatSense::VatPrice

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: VatSense::VatPrice,
        ?success: bool
      ) -> void

      def to_hash: -> { code: Integer, data: VatSense::VatPrice, success: bool }
    end
  end
end
