module VatSense
  module Models
    type rate =
      {
        country_code: String,
        country_name: String,
        eu: bool,
        object: VatSense::Models::Rate::object,
        other: ::Array[VatSense::Rate::Other]?,
        standard: VatSense::TaxRate
      }

    class Rate < VatSense::Internal::Type::BaseModel
      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader country_name: String?

      def country_name=: (String) -> String

      attr_reader eu: bool?

      def eu=: (bool) -> bool

      attr_reader object: VatSense::Models::Rate::object?

      def object=: (
        VatSense::Models::Rate::object
      ) -> VatSense::Models::Rate::object

      attr_accessor other: ::Array[VatSense::Rate::Other]?

      attr_reader standard: VatSense::TaxRate?

      def standard=: (VatSense::TaxRate) -> VatSense::TaxRate

      def initialize: (
        ?country_code: String,
        ?country_name: String,
        ?eu: bool,
        ?object: VatSense::Models::Rate::object,
        ?other: ::Array[VatSense::Rate::Other]?,
        ?standard: VatSense::TaxRate
      ) -> void

      def to_hash: -> {
        country_code: String,
        country_name: String,
        eu: bool,
        object: VatSense::Models::Rate::object,
        other: ::Array[VatSense::Rate::Other]?,
        standard: VatSense::TaxRate
      }

      type object = :rate

      module Object
        extend VatSense::Internal::Type::Enum

        RATE: :rate

        def self?.values: -> ::Array[VatSense::Models::Rate::object]
      end

      type other = { province: String? }

      class Other < VatSense::Models::TaxRate
        def province: -> String?

        def province=: (String? _) -> String?

        def initialize: (?province: String?) -> void

        def to_hash: -> { province: String? }
      end
    end
  end
end
