module VatSense
  module Models
    type rate_calculate_price_params =
      {
        price: String,
        tax_type: VatSense::Models::RateCalculatePriceParams::tax_type,
        country_code: String,
        eu: bool,
        ip_address: String,
        province_code: String,
        type: String
      }
      & VatSense::Internal::Type::request_parameters

    class RateCalculatePriceParams < VatSense::Internal::Type::BaseModel
      extend VatSense::Internal::Type::RequestParameters::Converter
      include VatSense::Internal::Type::RequestParameters

      attr_accessor price: String

      attr_accessor tax_type: VatSense::Models::RateCalculatePriceParams::tax_type

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader eu: bool?

      def eu=: (bool) -> bool

      attr_reader ip_address: String?

      def ip_address=: (String) -> String

      attr_reader province_code: String?

      def province_code=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (
        price: String,
        tax_type: VatSense::Models::RateCalculatePriceParams::tax_type,
        ?country_code: String,
        ?eu: bool,
        ?ip_address: String,
        ?province_code: String,
        ?type: String,
        ?request_options: VatSense::request_opts
      ) -> void

      def to_hash: -> {
        price: String,
        tax_type: VatSense::Models::RateCalculatePriceParams::tax_type,
        country_code: String,
        eu: bool,
        ip_address: String,
        province_code: String,
        type: String,
        request_options: VatSense::RequestOptions
      }

      type tax_type = :incl | :excl

      module TaxType
        extend VatSense::Internal::Type::Enum

        INCL: :incl
        EXCL: :excl

        def self?.values: -> ::Array[VatSense::Models::RateCalculatePriceParams::tax_type]
      end
    end
  end
end
