module VatSense
  module Models
    type rate_with_tax_rate =
      {
        country_code: String,
        country_name: String,
        eu: bool,
        object: VatSense::Models::RateWithTaxRate::object,
        tax_rate: VatSense::TaxRate
      }

    class RateWithTaxRate < VatSense::Internal::Type::BaseModel
      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader country_name: String?

      def country_name=: (String) -> String

      attr_reader eu: bool?

      def eu=: (bool) -> bool

      attr_reader object: VatSense::Models::RateWithTaxRate::object?

      def object=: (
        VatSense::Models::RateWithTaxRate::object
      ) -> VatSense::Models::RateWithTaxRate::object

      attr_reader tax_rate: VatSense::TaxRate?

      def tax_rate=: (VatSense::TaxRate) -> VatSense::TaxRate

      def initialize: (
        ?country_code: String,
        ?country_name: String,
        ?eu: bool,
        ?object: VatSense::Models::RateWithTaxRate::object,
        ?tax_rate: VatSense::TaxRate
      ) -> void

      def to_hash: -> {
        country_code: String,
        country_name: String,
        eu: bool,
        object: VatSense::Models::RateWithTaxRate::object,
        tax_rate: VatSense::TaxRate
      }

      type object = :rate

      module Object
        extend VatSense::Internal::Type::Enum

        RATE: :rate

        def self?.values: -> ::Array[VatSense::Models::RateWithTaxRate::object]
      end
    end
  end
end
