module VatSense
  module Models
    type rate_calculate_price_response =
      {
        code: Integer,
        data: VatSense::Models::RateCalculatePriceResponse::Data,
        success: bool
      }

    class RateCalculatePriceResponse < VatSense::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader data: VatSense::Models::RateCalculatePriceResponse::Data?

      def data=: (
        VatSense::Models::RateCalculatePriceResponse::Data
      ) -> VatSense::Models::RateCalculatePriceResponse::Data

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?code: Integer,
        ?data: VatSense::Models::RateCalculatePriceResponse::Data,
        ?success: bool
      ) -> void

      def to_hash: -> {
        code: Integer,
        data: VatSense::Models::RateCalculatePriceResponse::Data,
        success: bool
      }

      type data =
        {
          country_code: String,
          country_name: String,
          eu: bool,
          object: VatSense::Models::RateCalculatePriceResponse::Data::object,
          tax_rate: VatSense::TaxRate,
          vat_price: VatSense::VatPrice
        }

      class Data < VatSense::Internal::Type::BaseModel
        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader country_name: String?

        def country_name=: (String) -> String

        attr_reader eu: bool?

        def eu=: (bool) -> bool

        attr_reader object: VatSense::Models::RateCalculatePriceResponse::Data::object?

        def object=: (
          VatSense::Models::RateCalculatePriceResponse::Data::object
        ) -> VatSense::Models::RateCalculatePriceResponse::Data::object

        attr_reader tax_rate: VatSense::TaxRate?

        def tax_rate=: (VatSense::TaxRate) -> VatSense::TaxRate

        attr_reader vat_price: VatSense::VatPrice?

        def vat_price=: (VatSense::VatPrice) -> VatSense::VatPrice

        def initialize: (
          ?country_code: String,
          ?country_name: String,
          ?eu: bool,
          ?object: VatSense::Models::RateCalculatePriceResponse::Data::object,
          ?tax_rate: VatSense::TaxRate,
          ?vat_price: VatSense::VatPrice
        ) -> void

        def to_hash: -> {
          country_code: String,
          country_name: String,
          eu: bool,
          object: VatSense::Models::RateCalculatePriceResponse::Data::object,
          tax_rate: VatSense::TaxRate,
          vat_price: VatSense::VatPrice
        }

        type object = :rate

        module Object
          extend VatSense::Internal::Type::Enum

          RATE: :rate

          def self?.values: -> ::Array[VatSense::Models::RateCalculatePriceResponse::Data::object]
        end
      end
    end
  end
end
