module VatSense
  module Models
    type tax_rate =
      {
        class_: String,
        description: String,
        object: VatSense::Models::TaxRate::object,
        rate: Float,
        types: VatSense::Models::TaxRate::types
      }

    class TaxRate < VatSense::Internal::Type::BaseModel
      attr_reader class_: String?

      def class_=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader object: VatSense::Models::TaxRate::object?

      def object=: (
        VatSense::Models::TaxRate::object
      ) -> VatSense::Models::TaxRate::object

      attr_reader rate: Float?

      def rate=: (Float) -> Float

      attr_reader types: VatSense::Models::TaxRate::types?

      def types=: (
        VatSense::Models::TaxRate::types
      ) -> VatSense::Models::TaxRate::types

      def initialize: (
        ?class_: String,
        ?description: String,
        ?object: VatSense::Models::TaxRate::object,
        ?rate: Float,
        ?types: VatSense::Models::TaxRate::types
      ) -> void

      def to_hash: -> {
        class_: String,
        description: String,
        object: VatSense::Models::TaxRate::object,
        rate: Float,
        types: VatSense::Models::TaxRate::types
      }

      type object = :tax_rate

      module Object
        extend VatSense::Internal::Type::Enum

        TAX_RATE: :tax_rate

        def self?.values: -> ::Array[VatSense::Models::TaxRate::object]
      end

      type types = String | bool

      module Types
        extend VatSense::Internal::Type::Union

        def self?.variants: -> ::Array[VatSense::Models::TaxRate::types]
      end
    end
  end
end
